INSERT INTO `pet`( `personID`, `petName`, `species`, `requirements`) VALUES (1,'Amber','1','loves to have her butt scratched');
INSERT INTO `pet`( `personID`, `petName`, `species`, `requirements`) VALUES (3,'River','1','only barks when she wants attention from a human');
INSERT INTO `pet`( `personID`, `petName`, `species`, `requirements`) VALUES (3,'Storm','1','barks at everything');
INSERT INTO `pet`( `personID`, `petName`, `species`, `requirements`) VALUES (5,'Abby','1','loves to balance a dog biscuit on her nose and wait for your permission to eat it');
INSERT INTO `pet`( `personID`, `petName`, `species`, `requirements`) VALUES (5,'Rex','1','probably has Downs Syndrome, is not capable of pacing himself');
INSERT INTO `pet`( `personID`, `petName`, `species`, `requirements`) VALUES (7,'Opal','1','actually chases her tail for fun');
INSERT INTO `pet`( `personID`, `petName`, `species`, `requirements`) VALUES (9,'Stormie','1','does not tolerate cold weather well');
INSERT INTO `pet`( `personID`, `petName`, `species`, `requirements`) VALUES (11,'Gator','1','not an alligator (but will bite you)');
INSERT INTO `pet`( `personID`, `petName`, `species`, `requirements`) VALUES (13,'Firework','3','likely to die in the next three months');
INSERT INTO `pet`( `personID`, `petName`, `species`, `requirements`) VALUES (15,'Shadow','1','worlds biggest dog');
INSERT INTO `pet`( `personID`, `petName`, `species`, `requirements`) VALUES (17,'Casey','1','definitely a water dog');
INSERT INTO `pet`( `personID`, `petName`, `species`, `requirements`) VALUES (19,'Amus','1','NOT sweet like Famous Amus cookies--approach with caution');
INSERT INTO `pet`( `personID`, `petName`, `species`, `requirements`) VALUES (21,'Toby','1','somehow coexists with Amus');
INSERT INTO `pet`( `personID`, `petName`, `species`, `requirements`) VALUES (21,'Fatcat','2','ellusive cat that is fat');
INSERT INTO `pet`( `personID`, `petName`, `species`, `requirements`) VALUES (23,'Cisco','2','sibling of cat whose name I forgot');
INSERT INTO `pet`( `personID`, `petName`, `species`, `requirements`) VALUES (23,'Poncho','2','I think the other cat was named poncho?');
INSERT INTO `pet`( `personID`, `petName`, `species`, `requirements`) VALUES (1,'Madison','1','worldest freakiest dog');
INSERT INTO `pet`( `personID`, `petName`, `species`, `requirements`) VALUES (3,'Lucky','1','lives at the Stack');
INSERT INTO `pet`( `personID`, `petName`, `species`, `requirements`) VALUES (5,'Jesse','1','the dog belonging to Chase');
INSERT INTO `pet`( `personID`, `petName`, `species`, `requirements`) VALUES (7,'Balu','1','has some sort of skin condition');
INSERT INTO `pet`( `personID`, `petName`, `species`, `requirements`) VALUES (9,'Doerre','1','needs at least 10 acres of open space');
INSERT INTO `pet`( `personID`, `petName`, `species`, `requirements`) VALUES (11,'Scoobert Doo','1','also answers to Scooby-Doo, Scooby-Dooby-Doo, Scooby, and Scoob');
INSERT INTO `pet`( `personID`, `petName`, `species`, `requirements`) VALUES (13,'George','5','also responses to Curious George, often with the Man with the Yellow Hat');

